server:
  port: 8081
  
spring:
  cloud:
    config:
      server:
        git:
          default-label: jwt
          uri: https://github.com/kokyvr/microserive-code
          search-paths:
          - config-data
  application:
    name: config-service
